# Generated by Django 2.1.2 on 2018-10-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('proname', models.CharField(max_length=50)),
                ('productid', models.CharField(max_length=20)),
                ('part_name', models.CharField(max_length=50)),
                ('service_type', models.CharField(choices=[('SERVICE', 'SERVICE'), ('NEW ORDER', 'NEW ORDER')], default='SERVICE', max_length=10)),
                ('lab_number', models.DecimalField(decimal_places=0, max_digits=2)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
